# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 431)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_Repub = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cb_Repub.setGeometry(QtCore.QRect(40, 160, 53, 14))
        self.cb_Repub.setObjectName("cb_Repub")
        self.cb_Demo = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cb_Demo.setGeometry(QtCore.QRect(40, 180, 53, 14))
        self.cb_Demo.setObjectName("cb_Demo")
        self.cb_thrdprty = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cb_thrdprty.setGeometry(QtCore.QRect(40, 200, 53, 14))
        self.cb_thrdprty.setObjectName("cb_thrdprty")
        self.OK = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.OK.setGeometry(QtCore.QRect(90, 360, 116, 17))
        self.OK.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.OK.setObjectName("OK")
        self.label_VN = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_VN.setGeometry(QtCore.QRect(130, 10, 51, 16))
        self.label_VN.setObjectName("label_VN")
        self.Info = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Info.setEnabled(True)
        self.Info.setGeometry(QtCore.QRect(40, 30, 101, 121))
        self.Info.setReadOnly(True)
        self.Info.setObjectName("Info")
        self.customcan = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.customcan.setGeometry(QtCore.QRect(40, 220, 71, 20))
        self.customcan.setText("")
        self.customcan.setObjectName("customcan")
        self.name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name.setGeometry(QtCore.QRect(150, 30, 113, 20))
        self.name.setText("")
        self.name.setObjectName("name")
        self.phone = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.phone.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.label_Desc = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Desc.setGeometry(QtCore.QRect(50, 310, 221, 20))
        self.label_Desc.setObjectName("label_Desc")
        self.label_Nov30th = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Nov30th.setGeometry(QtCore.QRect(100, 330, 111, 21))
        self.label_Nov30th.setObjectName("label_Nov30th")
        self.dayvoted = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.dayvoted.setGeometry(QtCore.QRect(150, 90, 111, 31))
        self.dayvoted.setObjectName("dayvoted")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cb_Repub.setText(_translate("MainWindow", "Republican"))
        self.cb_Demo.setText(_translate("MainWindow", "Democrat"))
        self.cb_thrdprty.setText(_translate("MainWindow", "3rd party"))
        self.label_VN.setText(_translate("MainWindow", "VOTE NOW!"))
        self.Info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">canidates:<br /><br />Jane Doe (Republican)<br /><br />John Doe (Democrat)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Jonsey Doe (3rd Party)<br /><br />Joe Dohn (3rd Party)<br /><br />Dane Joe (3rd Party)</p></body></html>"))
        self.customcan.setPlaceholderText(_translate("MainWindow", "Canidate:"))
        self.name.setPlaceholderText(_translate("MainWindow", "Name:"))
        self.phone.setPlaceholderText(_translate("MainWindow", "Phone:"))
        self.label_Desc.setText(_translate("MainWindow", "Votes will be registered under name and phonenumber"))
        self.label_Nov30th.setText(_translate("MainWindow", "Votes will end November 30th"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
